# Generated by Django 2.1.7 on 2019-05-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_contenr',
            new_name='comment_content',
        ),
    ]
