# Generated by Django 2.1.7 on 2019-05-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190531_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_data']},
        ),
    ]
